ports:
  glutton_server: 5000

rules_path: rules/rules.yaml

producers:
  enabled: false
  gollum:
    enabled: false
    remote: http://gollum:gollum@localhost:9000
  hpfeeds:
    enabled: false
    host: 172.26.0.2
    port: 20000
    ident: ident
    auth: auth
    channel: test

conn_timeout: 45
max_tcp_payload: 4096
